export const content = {
  hero: {
    tagline: 'Marketing,\nwith governance.',
    taglineHighlight: 'governance.',
    subheading: 'データを、事業の意思決定言語にする。',
    body: [
      '個人事業主として、データガバナンス・WEBアナリティクス・アドテクを、上流の戦略から実装まで一人称で伴走します。',
      '代理店でもツールベンダーでもない、独立した第三者として。',
    ],
    pillars: [
      {
        number: '01',
        title: 'ガバナンス × 実装',
        description: '規程・ルール作成だけで終わらず、GA4・GTM・sGTM・CDPまで自分で触れる。',
      },
      {
        number: '02',
        title: '発注者目線の独立性',
        description: '媒体・ベンダーから独立した立場で意思決定を支援する。',
      },
      {
        number: '03',
        title: '個人だからこその密度',
        description: '顧問契約で「いつでも相談できるマーケ部門の隣の席」を実現。',
      },
    ],
    cta: { primary: '相談する', secondary: 'サービスを見る' },
  },
  services: {
    title: '5つの領域で、\nあなたの課題に応じます。',
    items: [
      {
        id: '01',
        slug: 'governance',
        label: 'Governance',
        title: 'データガバナンス & 基盤設計',
        summary: 'データの「定義」「責任」「品質」「ライフサイクル」を設計し、誰が見ても同じ意思決定ができる組織にします。',
        problems: [
          '部署ごとに数値の定義がバラバラで、会議が「数字合わせ」から始まる',
          'GA4・広告レポート・社内DWHで KPI が一致しない',
          '個人情報・同意管理（CMP / 改正電通法）への対応が止まっている',
          'データ基盤を作ったが、誰が・何のために使っているか説明できない',
        ],
        deliverables: [
          'データ定義書（メトリック・ディメンション・粒度）',
          'データガバナンス規程（責任分担・承認フロー）',
          '同意管理・プライバシー対応設計（CMP / Consent Mode v2）',
          'データ品質モニタリング設計（dbt / BigQuery）',
          '社内向け運用ドキュメント & 研修',
        ],
        process: [
          { step: '01', title: '現状ヒアリング', desc: '関係部署 5〜10名へのインタビューと既存ドキュメント精査（2週間）' },
          { step: '02', title: '課題整理 & 優先順位付け', desc: '影響度 × 着手しやすさで施策マップを作成（1週間）' },
          { step: '03', title: '規程・設計書の作成', desc: '定義書・規程・運用フローを起案、関係者レビュー（3〜6週間）' },
          { step: '04', title: '実装支援 & 浸透', desc: 'GA4 / GTM / dbt 等の実装を伴走、社内研修を実施（4〜12週間）' },
        ],
        forWho: ['年商 10億〜500億規模の事業会社', 'CDP・DWH 導入検討中の組織', 'プライバシー法対応をこれから始める組織'],
      },
      {
        id: '02',
        slug: 'analytics',
        label: 'Analytics',
        title: 'WEBアナリティクス & GA4移行',
        summary: 'GA4・GTM・sGTM・Looker Studio を「自社の意思決定言語」になるよう設計・実装します。',
        problems: [
          'GA4 に移行したが、UA時代のレポートが再現できない',
          'イベント設計が場当たり的で、データが集まっても活用できない',
          'sGTM（サーバーサイドGTM）に興味があるが、判断材料がない',
          'Looker Studio のダッシュボードが「眺めるだけ」になっている',
        ],
        deliverables: [
          'GA4 計測設計書（カスタムイベント・ディメンション設計）',
          'GTM コンテナ実装（クライアント / サーバーサイド）',
          'BigQuery エクスポート設計 & SQL クエリ集',
          'Looker Studio ダッシュボード（経営 / 運用 / 個別施策）',
          '計測タグ・データレイヤー仕様書',
        ],
        process: [
          { step: '01', title: '事業 KPI とユーザー行動の整理', desc: '何を測ると意思決定に効くかから逆算（1〜2週間）' },
          { step: '02', title: '計測設計', desc: 'イベント・パラメータ・コンバージョン設計（2〜3週間）' },
          { step: '03', title: 'GTM / sGTM 実装', desc: 'タグ・トリガー・変数の構築、QAテスト（3〜6週間）' },
          { step: '04', title: '可視化 & 運用引き継ぎ', desc: 'BigQuery / Looker Studio 構築、社内研修（2〜4週間）' },
        ],
        forWho: ['UA → GA4 移行を完遂したい組織', 'sGTM 採用を検討中の EC・SaaS', 'BigQuery で自由分析したい組織'],
      },
      {
        id: '03',
        slug: 'adtech',
        label: 'AdTech',
        title: '広告運用 & アドテク戦略',
        summary: '代理店任せにせず、媒体 API・タグ・計測の全レイヤーを発注者側で「読める」状態にします。',
        problems: [
          'Cookie 規制下で広告効果が読めなくなってきた',
          '代理店レポートを鵜呑みにせず、自社で検証したい',
          'Conversion API / Enhanced Conversions の実装が止まっている',
          'MMM（マーケミックスモデリング）や Incrementality 計測を試したい',
        ],
        deliverables: [
          '広告計測アーキテクチャ設計（Cookieless 前提）',
          'Conversion API / Enhanced Conversions 実装',
          '代理店レポート監査 & 媒体直接データとの突合',
          '入札戦略 & 配信設計のレビュー',
          'Incrementality / MMM 試行支援',
        ],
        process: [
          { step: '01', title: '現状計測の監査', desc: '媒体・GTM・サーバー側の計測経路を可視化（2週間）' },
          { step: '02', title: 'Cookieless 設計', desc: 'sGTM / CAPI / Consent Mode の組み合わせを設計（2〜3週間）' },
          { step: '03', title: '実装 & 検証', desc: '段階的に実装、A/B で効果検証（4〜8週間）' },
          { step: '04', title: '運用知見の社内化', desc: '代理店との分担再設計、社内ナレッジ化（継続）' },
        ],
        forWho: ['月間広告費 500万〜1億規模の事業会社', '代理店をセカンドオピニオン的に使いたい組織', '広告効果を経営報告に耐える形にしたい組織'],
      },
      {
        id: '04',
        slug: 'lifecycle',
        label: 'MA・CRM',
        title: 'ライフサイクル & グロース',
        summary: '獲得後の顧客行動を継続的に計測し、リテンション・LTV を伸ばす運用に組み替えます。',
        problems: [
          'MA・CRM ツールは導入したが、配信シナリオが固定化している',
          '顧客セグメントが「アクティブ / 非アクティブ」程度しかない',
          'LTV を計算しているが、施策に紐づけられていない',
          'プロダクト・マーケ・CS のデータが分断されている',
        ],
        deliverables: [
          'カスタマージャーニー & イベントマップ',
          'セグメンテーション設計（行動 × 属性 × 価値）',
          'ライフサイクル別シナリオ設計（オンボード / リテンション / 復帰）',
          'LTV / コホート分析ダッシュボード',
          'プロダクト × マーケ統合計測設計',
        ],
        process: [
          { step: '01', title: '現状顧客理解', desc: '既存データから顧客フェーズを定義、ボトルネック特定（2〜3週間）' },
          { step: '02', title: 'シナリオ設計', desc: '優先 3〜5 シナリオを KPI とセットで設計（2週間）' },
          { step: '03', title: 'MA / CDP 実装', desc: '使用ツール内でシナリオ実装・配信テスト（4〜8週間）' },
          { step: '04', title: '改善ループ確立', desc: 'KPI モニタリングと月次改善会議の運用化（継続）' },
        ],
        forWho: ['SaaS / EC / サブスク事業者', 'MA を導入済みだが効果が頭打ちの組織', 'LTV ベースの経営に切り替えたい組織'],
      },
      {
        id: '05',
        slug: 'ai-ml',
        label: 'AI・ML',
        title: 'AI・ML活用 & データサイエンス',
        summary: 'AI を「使う側」と「作る側」の両方の解像度で、現実的に効く活用ポイントを設計・実装します。',
        problems: [
          '生成 AI を業務に入れたいが、何から始めるか定まらない',
          '需要予測・LTV 予測・解約予測を内製したい',
          'BI 上で「異常検知」「自動アラート」を仕込みたい',
          'AI 関連ベンダー提案の良し悪しを判断できる人がいない',
        ],
        deliverables: [
          'AI 活用ロードマップ（半年〜2年）',
          'PoC（解約予測 / LTV 予測 / 需要予測 等）',
          'BigQuery ML / Vertex AI / OpenAI API 実装',
          'AI 出力の業務組込み設計（Slack / 社内ツール連携）',
          'ベンダー RFP 作成 & 提案評価支援',
        ],
        process: [
          { step: '01', title: 'ユースケース整理', desc: '事業課題から AI で解くべき問題を選定（2週間）' },
          { step: '02', title: '小さく PoC', desc: '1ユースケースを 4〜6 週間で実装、効果検証' },
          { step: '03', title: '本番運用化', desc: '監視・再学習・例外処理を含む運用設計（4〜8週間）' },
          { step: '04', title: '横展開 & 内製化', desc: '社内に知見移転、次のユースケースへ' },
        ],
        forWho: ['データ基盤がある程度整っている組織', 'PoC で終わらせず本番運用したい組織', 'AI 内製チームを育てたい組織'],
      },
    ],
  },
  engagements: {
    title: '4つの契約形態から、\n選べます。',
    items: [
      {
        title: 'Audit',
        description: '2〜4週間で現状を診断し、優先順位をつけたレポートを納品します。',
        price: '¥30万〜¥80万',
      },
      {
        title: 'Project',
        description: '課題が特定済みのチームに、設計から実装まで踏み込んで伴走します。',
        price: '¥100万〜¥600万',
      },
      {
        title: 'Advisor',
        description: '月額固定で「いつでも相談できるマーケ部門の隣の席」を担います。',
        price: '¥25万〜¥50万/月',
        highlight: true,
      },
      {
        title: 'Fractional',
        description: 'Head of Data / Marketing として、期間限定で週1〜2日コミットします。',
        price: '個別見積もり',
      },
    ],
  },
  contact: {
    title: 'Contact',
    heading: 'まずは、課題を聞かせてください。',
    intro: '初回30分の壁打ちは無料です。\n「これがやりたい」が定まっていない段階のご相談も歓迎します。',
    email: 'info@ambit.go2020.tokyo',
    responseTime: '原則 2 営業日以内に返信します。',
    methods: [
      {
        label: 'Email',
        value: 'info@ambit.go2020.tokyo',
        href: 'mailto:info@ambit.go2020.tokyo',
        note: '最も確実な連絡手段です',
      },
    ],
    fields: [
      { name: 'company', label: '会社名・組織名', required: true, type: 'text' },
      { name: 'name', label: 'お名前', required: true, type: 'text' },
      { name: 'email', label: 'メールアドレス', required: true, type: 'email' },
      { name: 'role', label: 'ご担当領域', required: false, type: 'text', placeholder: '例：マーケティング責任者 / データ基盤担当' },
      { name: 'budget', label: 'ご予算感（任意）', required: false, type: 'select', options: ['Audit（〜¥80万）', 'Project（¥100万〜¥600万）', 'Advisor（¥25万〜¥50万/月）', 'Fractional（要相談）', 'まだ決まっていない'] },
      { name: 'message', label: 'ご相談内容', required: true, type: 'textarea', placeholder: '現状の課題、聞きたいこと、検討しているサービスなど' },
    ],
  },
};
